const fs=require('node:fs'),assert=require('node:assert/strict'),path=require('node:path');
const {chromium}=require(process.env.JKCREW_PLAYWRIGHT_PATH||'playwright');const root=path.resolve(__dirname,'..'),app=fs.readFileSync(path.join(root,'app.js'),'utf8');
const code=app.slice(app.indexOf('function pointsReceiptAttributes('),app.indexOf('async function getPointHistory('));
(async()=>{const browser=await chromium.launch({headless:true,executablePath:process.env.JKCREW_BROWSER_PATH});const page=await browser.newPage({viewport:{width:390,height:667}});const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.setContent('<body><main id="host"></main></body>');await page.addStyleTag({content:fs.readFileSync(path.join(root,'styles.css'),'utf8')});
await page.addScriptTag({content:`const escapeHtml=s=>String(s).replaceAll('<','&lt;').replaceAll('"','&quot;');const messageFrom=e=>e.message;window.navigationCount=0;window.calls=[];const client={rpc:async(name,args)=>{calls.push(args);return {data:{scope:args.p_scope,total:15,raw_total:15,rows:[{label:'Bonus trick',detail:'Cannon Ball',points:5,events:1},{label:'Weekly challenge',detail:'Extra 5',points:5,events:1},...Array.from({length:30},(_,i)=>({label:'Training',detail:'Award '+i,points:0,events:1}))]}};}};${code}
document.querySelector('#host').innerHTML='<button id="rider"><span '+pointsReceiptAttributes('synthetic','all_time_points')+'>15 pts</span></button>';document.querySelector('#rider').onclick=()=>navigationCount++;`});
await page.locator('[data-points-receipt]').click();await page.getByText('Bonus trick',{exact:true}).waitFor();assert.equal(await page.evaluate(()=>navigationCount),0);assert.equal(await page.evaluate(()=>calls[0].p_scope),'all_time');assert(await page.getByText('Weekly challenge',{exact:true}).isVisible());assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
await page.locator('.points-receipt-dialog').hover();await page.mouse.wheel(0,2000);await page.waitForTimeout(200);assert(await page.locator('.points-receipt-dialog').evaluate(e=>e.scrollTop>0));assert(await page.getByRole('button',{name:'Close points receipt'}).isVisible());await page.getByRole('button',{name:'Close points receipt'}).click();assert.equal(await page.locator('dialog').count(),0);
await page.locator('[data-points-receipt]').focus();await page.keyboard.press('Enter');await page.getByText('Bonus trick',{exact:true}).waitFor();assert.equal(await page.evaluate(()=>navigationCount),0);assert.deepEqual(errors,[]);await browser.close();console.log('PASS: mobile receipt opens on score tap/keyboard, preserves rider navigation, shows challenge and bonus separately, scrolls with reachable close and uses all-time scope.');
})().catch(e=>{console.error(e);process.exit(1)});
