-- HOTBOX is the retired short name for the AUS National Training Facility.
-- Keep historical award text intact, but make every database consumer resolve
-- both names to the same venue identity used by the app.

create or replace function private.jkcrew_venue_key(p_venue text)
returns text
language sql
immutable
parallel safe
set search_path = pg_catalog
as $function$
  with normalized as (
    select lower(regexp_replace(btrim(coalesce(p_venue, '')), '[^[:alnum:]]+', '', 'g')) as venue_key
  )
  select case normalized.venue_key
    when 'beenleighskatepark' then 'beenleigh'
    when 'hotbox' then 'hotboxausnationaltrainingfacility'
    else normalized.venue_key
  end
  from normalized;
$function$;

revoke all on function private.jkcrew_venue_key(text) from public, anon, authenticated;

-- Rebuild expression indexes because their stored keys were generated by the
-- previous immutable function definition.
reindex index public.assignment_point_awards_park_session_idx;
reindex index public.weekly_trick_assignments_latest_daily_location_idx;

-- Recalculate the merged park once. refresh_park_king also removes the stale
-- duplicate snapshot whose old key was simply "hotbox".
select private.refresh_park_king('HOTBOX - Aus National Training Facility', null);
